name = "Fabulously Janked"
author = "Kneelawk"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82d22492d47913075f3f9c373a5af5e7622f67a2d3493b7abe900c6c0b5656b4"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
