name = "Fabulously Janked"
author = "Kneelawk"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6482b384cec8002c9327478a113219d76f827daafd0821188b617f74d34dcaca"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
