name = "Fabulously Janked"
author = "Kneelawk"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "097f069b5030659885e86da8f3ede3bad756af10769e99a99f5dba948724f30b"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
