name = "Fabulously Janked"
author = "Kneelawk"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83c438ea3b85cba9bbc1da7b20efa9363d4fe2b90665e7908b810ba4a8c25d75"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
