name = "Fabulously Janked"
author = "Kneelawk"
version = "1.3.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f33a6ab82ba8eccfb2ea6ecee5653553b51a602c5f27d79e90f1b101aed76b7f"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
